POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "Cayque Silva",
    "email": "cayque.silva@teste.com"
}


###
GET http://localhost:3333/invites/testeuser123



###
GET http://localhost:3333/subscribers/testeuser123/ranking/clicks